apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jenkins
  name:  claim-jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi