apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/ec2-user/